In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_excel(r"C:\Users\Rohit\Desktop\Machine Learning\SkinSegmentation.xlsx")
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 245057 entries, 0 to 245056
Data columns (total 4 columns):
B              245057 non-null int64
G              245057 non-null int64
R              245057 non-null int64
SKINNONSKIN    245057 non-null int64
dtypes: int64(4)
memory usage: 7.5 MB


In [2]:
dataset.describe()

B              G              R    SKINNONSKIN
count  245057.000000  245057.000000  245057.000000  245057.000000
mean      125.065446     132.507327     123.177151       1.792461
std        62.255653      59.941197      72.562165       0.405546
min         0.000000       0.000000       0.000000       1.000000
25%        68.000000      87.000000      70.000000       2.000000
50%       139.000000     153.000000     128.000000       2.000000
75%       176.000000     177.000000     164.000000       2.000000
max       255.000000     255.000000     255.000000       2.000000

In [3]:
feature_coloumn= ["B","G","R"]
X = dataset[feature_coloumn]
y = dataset.SKINNONSKIN

In [4]:
print(X)

          B    G    R
0        74   85  123
1        73   84  122
2        72   83  121
3        70   81  119
4        70   81  119
...     ...  ...  ...
245052  163  162  112
245053  163  162  112
245054  163  162  112
245055  163  162  112
245056  255  255  255

[245057 rows x 3 columns]


In [5]:
print(y)

0         1
1         1
2         1
3         1
4         1
         ..
245052    2
245053    2
245054    2
245055    2
245056    2
Name: SKINNONSKIN, Length: 245057, dtype: int64


In [6]:
X = dataset.iloc[:, :3].values
y = dataset.iloc[:,3].values

In [7]:
print(X)

[[ 74  85 123]
 [ 73  84 122]
 [ 72  83 121]
 ...
 [163 162 112]
 [163 162 112]
 [255 255 255]]


In [8]:
print(y)

[1 1 1 ... 2 2 2]


In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2,random_state = 0)

In [10]:
print("X_train Values:")
print(X_train)
print(X_train.shape)
print("---------------------")
print("y_train Values:")
print(y_train)
print(y_train.shape)

X_train Values:
[[121  79   4]
 [180 178 130]
 [  7  45  33]
 ...
 [183 179 138]
 [102 145 212]
 [128 135 168]]
(196045, 3)
---------------------
y_train Values:
[2 2 2 ... 2 1 2]
(196045,)


In [11]:
from sklearn.preprocessing import StandardScaler
sca = StandardScaler()
X_train = sca.fit_transform(X_train)
X_test = sca.transform(X_test)

## Logistic Regression

In [12]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(X_train,y_train)

C:\Users\Rohit\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=0, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [13]:
y_pred = classifier.predict(X_test)

In [14]:
from sklearn.metrics import confusion_matrix, classification_report
print("Confusion Matrix:\n",confusion_matrix(y_test, y_pred))
print("Classification report:\n",classification_report(y_test, y_pred))


Confusion Matrix:
 [[ 8370  1777]
 [ 2182 36683]]
Classification report:
               precision    recall  f1-score   support

           1       0.79      0.82      0.81     10147
           2       0.95      0.94      0.95     38865

    accuracy                           0.92     49012
   macro avg       0.87      0.88      0.88     49012
weighted avg       0.92      0.92      0.92     49012



In [15]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("\nMSE:",metrics.mean_squared_error(y_test,y_pred))

Accuracy: 0.919223863543622

MSE: 0.08077613645637803


## K-Nearest Neighbors

In [16]:
from sklearn.neighbors import KNeighborsClassifier
classifier1 = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p=2)
classifier1.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [17]:
y_pred1 = classifier1.predict(X_test)

In [18]:
from sklearn.metrics import confusion_matrix
print("Confusion Matrix:\n",confusion_matrix(y_test, y_pred1))

Confusion Matrix:
 [[10147     0]
 [   24 38841]]


In [19]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test, y_pred1))
print("\nMSE:",metrics.mean_squared_error(y_test,y_pred1))

Accuracy: 0.9995103240022851

MSE: 0.0004896759977148454


## Random Forest Classifier

In [20]:
from sklearn.ensemble import RandomForestClassifier
classifier2 = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier2.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [21]:
y_pred2 = classifier2.predict(X_test)

In [22]:
from sklearn.metrics import confusion_matrix
print("Confusion Matrix:\n",confusion_matrix(y_test, y_pred2))

Confusion Matrix:
 [[10146     1]
 [   25 38840]]


In [23]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test, y_pred2))
print("\nMSE:",metrics.mean_squared_error(y_test,y_pred2))

Accuracy: 0.9994695176691423

MSE: 0.0005304823308577492


In [95]:
from matplotlib.colors import ListedColormap
X_set, y_set = X_train, y_train
X0, X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 1, stop = X_set[:, 0].max() + 1, step = 0.01),
                         np.arange(start = X_set[:, 1].min() - 1, stop = X_set[:, 1].max() + 1, step = 0.01),
                         np.arange(start = X_set[:, 2].min() - 1, stop = X_set[:, 2].max() + 1, step = 0.01))

Z_train = np.array([X1.ravel(), X2.ravel()]).T
plt.contourf(X1, X2, classifier.predict(Z_train).reshape(X1.shape),  alpha=0.75, cmap=ListedColormap(('red', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 1], X_set[y_set == j, 2],
                c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('Random Forest Classification (Training set)')
plt.xlabel('Age')
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()

ValueError: X has 2 features per sample; expecting 3